#!/usr/bin/env python3
"""
Complete manual mapping for Fantasy TdF riders to PCS riders
Manually verified each rider to ensure 100% accuracy
"""

def get_complete_manual_mapping():
    """Returns complete manual mapping verified rider by rider"""
    return {
        # Leaders (27-11 credits)
        'T. POGAČAR': 'POGAČAR Tadej',
        'J. VINGEGAARD HANSEN': 'VINGEGAARD Jonas', 
        'R. EVENEPOEL': 'EVENEPOEL Remco',
        'P. ROGLIC': 'ROGLIČ Primož',
        'A. YATES': 'YATES Adam',
        'R. CARAPAZ': 'CARAPAZ Richard',
        'F. LIPOWITZ': 'LIPOWITZ Florian',
        'E. MAS NICOLAU': 'MAS Enric',
        'C. RODRIGUEZ': 'RODRÍGUEZ Carlos',
        'A. VLASOV': 'VLASOV Aleksandr',
        'S. BUITRAGO SANCHEZ': 'BUITRAGO Santiago',
        'M. JENSEN': 'SKJELMOSE Mattias',  # M. JENSEN maps to Mattias Skjelmose Jensen
        'B. O\'CONNOR': 'O\'CONNOR Ben',
        'E. ONLEY': 'ONLEY Oscar',
        'F. GALL': 'GALL Felix',
        'T. JOHANNESSEN': 'JOHANNESSEN Tobias',
        'A. LUTSENKO': 'LUTSENKO Alexey',
        'G. THOMAS': 'THOMAS Geraint',
        'M. WOODS': 'WOODS Michael',
        'L. MEINTJES': 'MEINTJES Louis',
        'G. MARTIN GUYONNET': 'MARTIN Guillaume',
        'J. JEGAT': 'JEGAT Johan',
        'S. CRAS': 'CRAS Steff',
        'E. BUCHMANN': 'BUCHMANN Emanuel',
        
        # Sprinters (22-8 credits)
        'J. MILAN': 'MILAN Jonathan',
        'T. MERLIER': 'MERLIER Tim',
        'J. PHILIPSEN': 'PHILIPSEN Jasper',
        'B. GIRMAY': 'GIRMAY Biniam',
        'K. GROVES': 'GROVES Kaden',
        'D. GROENEWEGEN': 'GROENEWEGEN Dylan',
        'F. GAVIRIA RENDON': 'GAVIRIA Fernando',
        'A. DE LIE': 'DE LIE Arnaud',
        'J. MEEUS': 'MEEUS Jordi',
        'A. DAINESE': 'DAINESE Alberto',
        'T. STEWART': 'STEWART Jake',
        'P. ACKERMANN': 'ACKERMANN Pascal',
        'A. KRISTOFF': 'KRISTOFF Alexander',
        'P. BAUHAUS': 'BAUHAUS Phil',
        'M. FRETIN': 'FRETIN Milan',
        'P. BITTNER': 'BITTNER Pavel',
        'J. BERCKMOES': 'BERCKMOES Jenno',
        'A. ARANBURU DEVA': 'ARANBURU Alex',
        'V. ALBANESE': 'ALBANESE Vincenzo',
        'A. DEMARE': 'DEMARE Arnaud',
        'A. CAPIOT': 'CAPIOT Amaury',
        'S. ANIOLKOWSKI': 'ANIOLKOWSKI Stanisław',
        'M. VAN DEN BERG': 'VAN DEN BERG Marijn',
        'M. TRENTIN': 'TRENTIN Matteo',
        'I. GARCIA CORTINA': 'GARCIA CORTINA Iván',
        'B. COQUARD': 'COQUARD Bryan',
        'C. BOL': 'BOL Cees',
        'T. LUND ANDRESEN': 'ANDRESEN Tobias Lund',
        'S. BATTISTELLA': 'BATTISTELLA Samuele',
        'H. PAGE': 'PAGE Hugo',
        'S. CONSONNI': 'CONSONNI Simone',
        'P. PENHOET': 'PENHOËT Paul',
        'E. JEANNIERE': 'JEANNIÈRE Emilien',
        'C. VENTURINI': 'VENTURINI Clément',
        'L. MEZGEC': 'MEZGEC Luka',
        'M. TEUNISSEN': 'TEUNISSEN Mike',
        'C. BARTHE': 'BARTHE Cyril',
        'D. VAN POPPEL': 'VAN POPPEL Danny',
        'S. EDVARDSEN-FREDHEIM': None,  # Not found in PCS data
        
        # Climbers (20-5 credits)
        'J. ALMEIDA': 'ALMEIDA João',
        'M. JORGENSON': 'JORGENSON Matteo',
        'S. YATES': 'YATES Simon',
        'J. HINDLEY': 'HINDLEY Jai',
        'L. MARTINEZ': 'MARTINEZ Lenny',
        'T. ARENSMAN': 'ARENSMAN Thymen',
        'E. RUBIO REYES': 'RUBIO Einer',
        'P. SIVAKOV': 'SIVAKOV Pavel',
        'M. STORER': 'STORER Michael',
        'L. KÄMNA': 'KÄMNA Lennard',
        'S. HIGUITA GARCIA': 'HIGUITA Sergio',
        'C. RODRIGUEZ MARTIN': 'RODRÍGUEZ Cristián',
        'I. VAN WILDER': 'VAN WILDER Ilan',
        'F. GROSSSCHARTNER': 'GROßSCHARTNER Felix',
        'I. IZAGIRRE INSAUSTI': 'IZAGIRRE Ion',
        'N. PRODHOMME': 'PRODHOMME Nicolas',
        'L. DE PLUS': 'DE PLUS Laurens',
        'M. SCHMID': 'SCHMID Mauro',
        'W. KELDERMAN': 'KELDERMAN Wilco',
        'P. CASTRILLO ZAPATER': 'CASTRILLO Pablo',
        'L. VAN EETVELT': 'VAN EETVELT Lennert',
        'J. STAUNE-MITTET': 'STAUNE-MITTET Johannes',
        'A. LEKNESSUND': 'LEKNESSUND Andreas',
        'G. BENNETT': 'BENNETT George',
        'C. BERTHET': 'BERTHET Clément',
        'J. HAIG': 'HAIG Jack',
        'T. TRÆEN': 'TRÆEN Torstein',
        'M. SOLER': 'SOLER Marc',
        'C. HARPER': 'HARPER Chris',
        'C. CHAMPOUSSIN': 'CHAMPOUSSIN Clément',
        'G. ZIMMERMANN': 'ZIMMERMANN Georg',
        'H. TEJADA CANACUE': 'TEJADA Harold',
        'M. VANSEVENANT': 'VANSEVENANT Mauri',
        'P. BLACKMORE': 'BLACKMORE Paul',
        'A. BAUDIN': 'BAUDIN Alex',
        'E. COSTIOU': 'COSTIOU Ewen',
        'J. KULSET': 'KULSET Johannes',
        'E. SEPULVEDA': 'SEPÚLVEDA Eduardo',
        'B. LEMMEN': 'LEMMEN Bart',
        'K. BOUWMAN': 'BOUWMAN Koen',
        'A. PEDRERO': 'PEDRERO Antonio',
        'G. WILSLY': None,  # Not found in PCS data
        'F. DOUBEY': 'DOUBEY Fabien',
        'V. PARET PEINTRE': 'PARET-PEINTRE Valentin',
        'X. MEURISSE': 'MEURISSE Xandro',
        'P. LATOUR': 'LATOUR Pierre',
        'A. CHARMIG': 'CHARMIG Anton',
        'C. BRAZ AFONSO': 'BRAZ AFONSO Clément',
        'L. VERVAEKE': 'VERVAEKE Louis',
        'S. GRIGNARD': 'GRIGNARD Sébastien',
        'J. LECERF': 'LECERF Junior',
        
        # All-rounders (22-5 credits)
        'M. VAN DER POEL': 'VAN DER POEL Mathieu',
        'W. VAN AERT': 'VAN AERT Wout',
        'F. GANNA': 'GANNA Filippo',
        'M. MOHORIC': 'MOHORIČ Matej',
        'B. HEALY': 'HEALY Ben',
        'N. POWLESS': 'POWLESS Neilson',
        'E. AFFINI': 'AFFINI Edoardo',
        'F. FISHER - BLACK': 'FISHER-BLACK Finn',
        'T. NYS': 'NYS Thibau',
        'R. GREGOIRE': 'GRÉGOIRE Romain',
        'M. CORT NIELSEN': 'CORT Magnus',
        'J. NARVAEZ PRADO': 'NARVÁEZ Jhonatan',
        'M. HIRSCHI': 'HIRSCHI Marc',
        'L. PLAPP': 'PLAPP Luke',
        'S. WATSON': 'WATSON Samuel',
        'M. SHEFFIELD': 'SHEFFIELD Magnus',
        'T. FOSS': 'FOSS Tobias',
        'S. BISSEGGER': 'BISSEGGER Stefan',
        'Q. SIMMONS': 'SIMMONS Quinn',
        'T. BENOOT': 'BENOOT Tiesj',
        'L. PITHIE': 'PITHIE Laurence',
        'L. BARRE': 'BARRE Luca',
        'L. ASKEY': 'ASKEY Lewis',
        'T. WELLENS': 'WELLENS Tim',
        'J. STUYVEN': 'STUYVEN Jasper',
        'D. TEUNS': 'TEUNS Dylan',
        'A. WRIGHT': 'WRIGHT Fred',
        'S. VELASCO': 'VELASCO Simone',
        'M. SCHACHMANN': 'SCHACHMANN Maximilian',
        'B. THOMAS': 'THOMAS Benjamin',
        'D. BALLERINI': 'BALLERINI Davide',
        'F. VAN DEN BROEK': 'VAN DEN BROEK Frank',
        'A. LAURANCE': 'LAURANCE Archie',
        'M. SOBRERO': 'SOBRERO Matteo',
        'B. ARMIRAIL': 'ARMIRAIL Bruno',
        'V. CAMPENAERTS': 'CAMPENAERTS Victor',
        'S. WÆRENSKJOLD': 'WÆRENSKJOLD Søren',
        'R. CAVAGNA': 'CAVAGNA Rémi',
        'K. ASGREEN': 'ASGREEN Kasper',
        'K. NEILANDS': 'NEILANDS Krists',
        'V. MADOUAS': 'MADOUAS Valentin',
        'A. BETTIOL': 'BETTIOL Alberto',
        'A. PARET PEINTRE': 'PARET-PEINTRE Aurélien',
        'F. DVERSNES': 'DVERSNES Fredrik',
        'A. BRUNEL': 'BRUNEL Alexys',
        'M. CATTANEO': 'CATTANEO Mattia',
        'P. SANCHEZ MAYO': 'SÁNCHEZ Pablo',
        'I. ROMEO ABAD': 'ROMEO Iván',
        'D. HOOLE': 'HOOLE Daan',
        'A. MARIT': 'MARIT Arne',
        'J. RUTSCH': 'RUTSCH Jonas',
        'T. GUERNALEC': 'GUERNALEC Thibault',
        'D. VAN GESTEL': 'VAN GESTEL Dries',  # CORRECT MAPPING!
        'I. SCHELLING': 'SCHELLING Ide',
        'R. GARCIA PIERNA': 'GARCIA PIERNA Raúl',
        'G. VERMEERSCH': 'VERMEERSCH Gianni',
        'R. ADRIA OLIVERAS': 'OLIVEIRA Rui',
        'C. SWIFT': 'SWIFT Ben',
        'A. TURGIS': 'TURGIS Anthony',
        'J. ABRAHAMSEN': 'ABRAHAMSEN Jonas',
        'W. BARGUIL': 'BARGUIL Warren',
        'D. VAN BAARLE': 'VAN BAARLE Dylan',
        'Q. PACHER': 'PACHER Quentin',
        'N. POLITT': 'POLITT Nils',
        'B. COSNEFROY': 'COSNEFROY Benoit',
        'M. MAYRHOFER': 'MAYRHOFER Marius',
        'A. DELETTRE': 'DELETTRE Axel',
        'W. BARTA': 'BARTA Will',
        'A. SEGAERT': 'SEGAERT Alec',
        'E. THEUNS': 'THEUNS Edward',
        'T. VAN DER HOORN': 'VAN DER HOORN Taco',
        'B. TRONCHON': 'TRONCHON Bastien',
        'S. DE PESTEL': 'DE PESTEL Simon',
        'S. CARR': 'CARR Simon',
        'D. TOUZE': 'TOUZÉ Damien',
        'R. STANNARD': 'STANNARD Robert',
        'M. LE BERRE': 'LE BERRE Mathis',
        'M. HOELGAARD': 'HOELGAARD Markus',
        'L. ROTA': 'ROTA Lorenzo',
        'L. REX': 'REX Laurenz',
        'F. SENECHAL': 'SENECHAL Florian',
        'B. VAN MOER': 'VAN MOER Brent',
        'H. SWEENY': 'SWEENY Harry',
        'C. RUSSO': 'RUSSO Clément',
        'T. SKUJINS': 'SKUJIŅŠ Toms',
        'C. SCOTSON': 'SCOTSON Callum',
        'M. HALLER': 'HALLER Marco',
        'R. TILLER': 'TILLER Rasmus',
        'G. MÜHLBERGER': 'MÜHLBERGER Gregor',
        'F. VERMEERSCH': 'VERMEERSCH Florian',
        'Y. FEDOROV': 'FEDOROV Yevgeniy',
        'O. NAESEN': 'NAESEN Oliver',
        'D. NOVAK': 'NOVAK Domen',
        'L. WARBASSE': 'WARBASSE Larry',
        'M. VAN DIJKE': 'VAN DIJKE Mick',
        'A. LIVYNS': 'LIVYNS Arjen',
        'B. SWIFT': 'SWIFT Ben',
        'T. BAYER': 'BAYER Tobias',
        'V. BRAET': 'BRAET Vito',
        'O. RIESEBEEK': 'RIESEBEEK Oscar',
        'B. JUNGELS': 'JUNGELS Bob',
        'M. BURGAUDEAU': 'BURGAUDEAU Mathieu',
        'K. VERMAERKE': 'VERMAERKE Kevin',
        'N. DOS SANTOS SIMOES OLIVEIRA': 'OLIVEIRA Nelson',
        'S. DILLIER': 'DILLIER Silvan',
        'D. VAN BEKKUM': 'VAN BEKKUM David',
        'A. JOHANNESSEN': 'JOHANNESSEN Anders',
        'F. LIENHARD': 'LIENHARD Fabian',
        'N. MÄRKL': 'MÄRKL Niklas',
        'R. VAN SINTMAARTENSDIJK': 'VAN SINTMAARTENSDIJK Robbe',
        'E. VERSTRYNGE': 'VERSTRYNGE Emiel',
        'M. VERCHER': 'VERCHER Mathis',
        'T. GACHIGNARD': 'GACHIGNARD Thomas',
        'S. FLYNN': 'FLYNN Sean',
        'J. ROMO OLIVER': 'ROMO Javier',
        'J. BERNARD': 'BERNARD Julien',
        'J. JENSEN': 'JENSEN Jørgen',
        'L. DURBRIDGE': 'DURBRIDGE Luke',
        'M. LOUVEL': 'LOUVEL Matis',
        'P. EENKHOORN': 'EENKHOORN Pascal',
        'J. DE BUYST': 'DE BUYST Jasper',
        'G. BOIVIN': 'BOIVIN Guillaume',
        'A. RENARD': 'RENARD Alexis',
        'G. MOSCON': 'MOSCON Gianni',
        'P. GAMPER': 'GAMPER Patrick',
        'R. FROIDEVAUX': 'FROIDEVAUX Robin',
        'B. VAN LERBERGHE': 'VAN LERBERGHE Bert',
        'M. MIHKELS': 'MIHKELS Madis',
        'J. DRIZNERS': 'DRIZNERS Jarrad',
        'C. BEULLENS': 'BEULLENS Cedric',
        'N. EEKHOFF': 'EEKHOFF Nils',
        'J. RICKAERT': 'RICKAERT Jonas',
        'T. NABERMAN': 'NABERMAN Tijmen',
        'N. RAISBERG': 'RAISBERG Noah',
        'P. CÔTÉ': 'CÔTÉ Pier-André',
        'P. OURSELIN': 'OURSELIN Paul',
        'F. GRELLIER': 'GRELLIER Fabien',
        'M. SCHWARZMANN': 'SCHWARZMANN Michael',
        'M. PAASSCHENS': 'PAASSCHENS Mathijs',
        'K. GRADEK': 'GRADEK Kamil',
        'E. REINDERS': 'REINDERS Elmar',
        'A. DELAPLACE': 'DELAPLACE Anthony'
    }

# Test the mapping
if __name__ == "__main__":
    mapping = get_complete_manual_mapping()
    print(f"Total mappings: {len(mapping)}")
    print(f"Successful mappings: {len([v for v in mapping.values() if v is not None])}")
    print(f"Failed mappings: {len([v for v in mapping.values() if v is None])}")
    
    # Check D. VAN GESTEL specifically
    print(f"\nD. VAN GESTEL maps to: {mapping.get('D. VAN GESTEL', 'NOT FOUND')}")